SET SERVEROUTPUT ON
BEGIN
  PKG_APP_CTX.SET_ID_USUARIO(1);
  DBMS_OUTPUT.PUT_LINE('APP_CTX.ID_USUARIO='||NVL(SYS_CONTEXT('APP_CTX','ID_USUARIO'),'NULL'));
  DBMS_OUTPUT.PUT_LINE('APP_PYME_CTX.ID_USUARIO='||NVL(SYS_CONTEXT('APP_PYME_CTX','ID_USUARIO'),'NULL'));
END;
/
