-- Solo reemplaza el BODY; el spec ya existe
CREATE OR REPLACE PACKAGE BODY PKG_APP_CTX AS
  PROCEDURE SET_ID_USUARIO(p_id NUMBER) IS
  BEGIN
    DBMS_SESSION.SET_CONTEXT('APP_CTX',       'ID_USUARIO', TO_CHAR(p_id));
    DBMS_SESSION.SET_CONTEXT('APP_PYME_CTX',  'ID_USUARIO', TO_CHAR(p_id));
  END;

  PROCEDURE CLEAR IS
  BEGIN
    DBMS_SESSION.CLEAR_CONTEXT('APP_CTX',      'ID_USUARIO');
    DBMS_SESSION.CLEAR_CONTEXT('APP_PYME_CTX', 'ID_USUARIO');
  END;
END PKG_APP_CTX;
/
SHOW ERRORS
