-- SPEC pública mínima
CREATE OR REPLACE PACKAGE PKG_APP_CTX AUTHID DEFINER AS
  PROCEDURE SET_ID_USUARIO(p_id NUMBER);
END PKG_APP_CTX;
/

-- BODY que setea el contexto APP_CTX
CREATE OR REPLACE PACKAGE BODY PKG_APP_CTX AS
  PROCEDURE SET_ID_USUARIO(p_id NUMBER) IS
  BEGIN
    DBMS_SESSION.SET_CONTEXT('APP_CTX','ID_USUARIO', p_id);
  END;
END PKG_APP_CTX;
/

-- Probar que funciona
BEGIN
  PKG_APP_CTX.SET_ID_USUARIO(1);  -- usa el ID que prefieras
END;
/
SELECT SYS_CONTEXT('APP_CTX','ID_USUARIO') AS ID_USUARIO FROM dual;
/
