SET HEADING OFF FEEDBACK ON PAGESIZE 100
PROMPT Refresh MV_VENTAS_POR_PRODUCTO...
BEGIN
  DBMS_MVIEW.REFRESH('MV_VENTAS_POR_PRODUCTO','C');
END;
/
PROMPT Row count:
SELECT COUNT(*) filas FROM MV_VENTAS_POR_PRODUCTO;
PROMPT Indexes:
SELECT index_name, status
FROM   user_indexes
WHERE  table_name = UPPER('MV_VENTAS_POR_PRODUCTO');
EXIT
