name: Liquibase – Validate & offline SQL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  liquibase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Valida los changelogs sin tocar DB
      - name: Liquibase Validate (no DB)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/db-project/liquibase:/liquibase/changelog" \
            liquibase/liquibase:4.33.0 \
            --defaultsFile=/liquibase/changelog/liquibase.properties \
            --changelog-file=/liquibase/changelog/changelog-master.xml \
            validate

      # Genera el SQL de update en modo offline (Oracle)
      - name: Liquibase updateSQL (offline Oracle)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/db-project/liquibase:/liquibase/changelog" \
            -w /liquibase/changelog \
            liquibase/liquibase:4.33.0 \
            --changelog-file=changelog-master.xml \
            --url="offline:oracle?version=21" \
            --defaultSchemaName=APP_PYME \
            update-sql | tee updateSQL-offline-oracle.sql

      - name: Publicar artefacto updateSQL
        uses: actions/upload-artifact@v4
        with:
          name: updateSQL-offline-oracle
          path: db-project/liquibase/updateSQL-offline-oracle.sql
          if-no-files-found: error
