name: CI Liquibase (offline)

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: liquibase-${{ github.ref }}
  cancel-in-progress: true

jobs:
  liquibase-offline:
    name: Validate & update-sql (offline)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mostrar estructura relevante
        run: |
          ls -la
          ls -la db-project/liquibase || true

      # VALIDATE (offline) usando el mismo layout que probaste local:
      # montamos db-project como /work y trabajamos en /work/liquibase
      - name: Liquibase validate (offline, !admin)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/db-project:/work" \
            -w /work/liquibase \
            liquibase/liquibase:4.33.0 \
            --changelog-file=changelog-master.xml \
            --url="offline:oracle?version=21" \
            --defaultSchemaName=APP_PYME \
            --contexts="!admin" \
            validate

      # UPDATE-SQL (offline) – genera el script y lo deja en el repo de trabajo
      - name: Liquibase update-sql (offline, !admin)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/db-project:/work" \
            -w /work/liquibase \
            liquibase/liquibase:4.33.0 \
            --changelog-file=changelog-master.xml \
            --url="offline:oracle?version=21" \
            --defaultSchemaName=APP_PYME \
            --contexts="!admin" \
            update-sql > /work/liquibase/updateSQL-offline-oracle.sql

      - name: Verificar tamaño del SQL generado
        run: |
          wc -l db-project/liquibase/updateSQL-offline-oracle.sql
          head -n 20 db-project/liquibase/updateSQL-offline-oracle.sql
          tail -n 20 db-project/liquibase/updateSQL-offline-oracle.sql

      - name: Subir artefacto (updateSQL)
        uses: actions/upload-artifact@v4
        with:
          name: updateSQL-offline-oracle
          path: db-project/liquibase/updateSQL-offline-oracle.sql
